spring.application.name=Starter Spring Boot

payment.provider=razorpay

#debug=true

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/starter}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
#spring.jpa.hibernate.ddl-auto=create-drop // this will create the schema when running the application and drop it as well when terminated
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Format the hibernate queries, statements
spring.jpa.properties.hibernate.format_sql=true